from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
ARTIFACT_DIR = PROJECT_ROOT / "artifacts"
AGGREGATES_DIR = ARTIFACT_DIR / "aggregates"
FIGURES_DIR = ARTIFACT_DIR / "figures"

ANALYSIS_BASE_PATH = ARTIFACT_DIR / "analysis_base.parquet"
DATA_PROFILE_PATH = ARTIFACT_DIR / "data_profile.json"
SCHEMA_REPORT_PATH = ARTIFACT_DIR / "schema_report.json"
TOPIC_SUMMARY_PATH = ARTIFACT_DIR / "topic_summary.csv"
WEEKLY_SUMMARY_PATH = ARTIFACT_DIR / "weekly_summary.md"
INSIGHT_CARDS_PATH = ARTIFACT_DIR / "insight_cards.json"

LOW_SCORE_MAX = 2
HIGH_SCORE_MIN = 4
RECENT_SHORT_DAYS = 7
RECENT_LONG_DAYS = 30
RATING_DROP_WINDOW_DAYS = 30
MIN_TITLE_REVIEWS_FOR_ALERT = 25
MAX_KEYWORDS = 25
MAX_TOPIC_REVIEWS = 120_000
MIN_REVIEWS_PER_TOPIC = 20
DEFAULT_TOPIC_COUNT = 12
DEFAULT_RANDOM_STATE = 42

REQUIRED_ARTIFACTS = [
    ANALYSIS_BASE_PATH,
    DATA_PROFILE_PATH,
    SCHEMA_REPORT_PATH,
    TOPIC_SUMMARY_PATH,
    WEEKLY_SUMMARY_PATH,
    INSIGHT_CARDS_PATH,
]

